### ISSUE TITLE
FTBS docker.go undefined volume.Request volume.Response etc

### ISSUE THREAD

**Issue by babs** [cgt212/cassfs#4]
I'm trying to build cassfs but I got the following error.
Did I missed a step or something has changed on a dependency ?

    $ LC_ALL=C make linux
    #go generate ./...
    GOOS=linux GOARCH=amd64 go build -o cassfs -ldflags '-X "main.BuiltOn=Sun Oct  1 19:11:19 CEST 2017" -X "main.CommitHash=5e8fe3782ff1b99de4691b61cbb19f69e47dc95a" -s -w' .
    # github.com/cgt212/cassfs/driver
    ../../../go/src/github.com/cgt212/cassfs/driver/docker.go:96:33: undefined: volume.Request
    ../../../go/src/github.com/cgt212/cassfs/driver/docker.go:96:49: undefined: volume.Response
    ../../../go/src/github.com/cgt212/cassfs/driver/docker.go:104:33: undefined: volume.Request
    ../../../go/src/github.com/cgt212/cassfs/driver/docker.go:104:49: undefined: volume.Response
    ../../../go/src/github.com/cgt212/cassfs/driver/docker.go:163:33: undefined: volume.Request
    ../../../go/src/github.com/cgt212/cassfs/driver/docker.go:163:49: undefined: volume.Response
    ../../../go/src/github.com/cgt212/cassfs/driver/docker.go:181:53: undefined: volume.Response
    ../../../go/src/github.com/cgt212/cassfs/driver/docker.go:216:57: undefined: volume.Response
    ../../../go/src/github.com/cgt212/cassfs/driver/docker.go:245:31: undefined: volume.Request
    ../../../go/src/github.com/cgt212/cassfs/driver/docker.go:245:47: undefined: volume.Response
    ../../../go/src/github.com/cgt212/cassfs/driver/docker.go:245:31: too many errors
    Makefile:19: recipe for target 'linux' failed
    make: *** [linux] Error 2

**Comment by cgt212** [comment]
The docker volume driver changed types.  The driver code is updated to work with the new types.  It should compile now.

**Comment by babs** [comment]
It works like a charm.
